### PR TITLE
Exclude private API calls from swagger

### PR DESCRIPTION
**Pull request by burov**
If we use atlas_patch and  tagged  our rpc method as "private" see example  below
```
rpc Update (UpdateNetworkRequest) returns (UpdateNetworkResponse) {
    option (google.api.http) = {
      put: "/network/{payload.id.resource_id}"
      body: "payload"

      additional_bindings {
        patch: "/network/{payload.id.resource_id}",
        body:  "payload"
      }

    };
    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
      tags: "private"
    };
  }
```
this method will be excluded from service.swagger.json, but if we specified with_private=true flag, plugin will generate service.private.swagger.json with all possible operation for path

### CODE REVIEW

**Comment by askurydzin** [comment]
and what happens to a models (for example UpdateNetworkRequest), should it be also excluded from scheme. From other side, should it be left dangling when no 'public' call left using it?

**Comment by burov** [comment]
Yes, you right i forgot about model in definition section, I think i can remove i from public swagger file, thanks

**Review by askurydzin — APPROVED** [review]
LGTM

**Comment by Evgeniy-L** [comment]
why do we have so many changes in Gopkg.lock?

**Comment by burov** [comment]
Because dependencies are outdated

**Review by Evgeniy-L — APPROVED** [review]

**Pull request merged**
