### PR TITLE
add field annotation for example customization

### PR DESCRIPTION
**Pull request by burov**
Add custom annotation for custom example presentation 

You can use annotation like presented below 

(grpc.gateway.protoc_gen_swagger.options.openapiv2_field).example.string_value = "Hello World"
(grpc.gateway.protoc_gen_swagger.options.openapiv2_field).example.number_value = 5
(grpc.gateway.protoc_gen_swagger.options.openapiv2_field).example.bool_value = true

### CODE REVIEW

**Comment by askurydzin** [comment]
Could you please add short code-snippets of schemes that are rendered with these values? I mean, show how list, struct values are expected to be rendered and so on.

**Comment by askurydzin** [comment]
maybe it makes sense to define dedicated message for it?

```
message OpenAPIExample {
    string string = 1;
    int32 int32 = 2;
    bool bool = 3;
    repeated Repeated = 4;
    message Repeated {
        repeated int32 int32 = 1;
        .... 
```

so that example.string = "aaa"
example.repeated = {string: ["x", "y"]}

**Comment by burov** [comment]
@askurydzin  We will think about it, and try to find the best approach

**Review by askurydzin — APPROVED** [review]
OK, so basically implementation LGTM, if you're in a prototyping stage and willing to demo it as soon as possible you can go on with merge.

However for now I can hardly imagine if someone (me :)) would like to use following to specify that some value is a list that may have IPv4 or IPv6 addresses as values:

```
(grpc.gateway.protoc_gen_swagger.options.openapiv2_field).example.list_value = {
    values: [
        {string_value: "10.1.2.23"}, {string_value: "2001:db1::1"}
    ]
} 
```

**Pull request closed without merging**
